/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class EditorTexto extends javax.swing.JFrame {

    /**
     * Creates new form EditorTexto
     */
    public EditorTexto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaEditor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuArchivo = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmItemCortar = new javax.swing.JMenuItem();
        jmItemCopiar = new javax.swing.JMenuItem();
        jmItemPegar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmnuFuente = new javax.swing.JMenu();
        jmItemCourierNew = new javax.swing.JMenuItem();
        jmItemnArial = new javax.swing.JMenuItem();
        jmItemFPredeterminada = new javax.swing.JMenuItem();
        jmnuTamaño = new javax.swing.JMenu();
        jmItem16 = new javax.swing.JMenuItem();
        jmItem24 = new javax.swing.JMenuItem();
        jmItemPredeterminado = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tijeras.png"))); // NOI18N
        jButton1.setToolTipText("Cortar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copiar.png"))); // NOI18N
        jButton2.setToolTipText("Cortar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pegar.png"))); // NOI18N
        jButton3.setToolTipText("Pegar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jtxtaEditor.setColumns(20);
        jtxtaEditor.setRows(5);
        jScrollPane1.setViewportView(jtxtaEditor);

        jmnuArchivo.setMnemonic('A');
        jmnuArchivo.setText("Archivo");

        jmItemSalir.setMnemonic('S');
        jmItemSalir.setText("Salir");
        jmItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalirActionPerformed(evt);
            }
        });
        jmnuArchivo.add(jmItemSalir);

        jMenuBar1.add(jmnuArchivo);

        jMenu2.setText("Edición ");

        jmItemCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCortar.setMnemonic('T');
        jmItemCortar.setText("Cortar");
        jmItemCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCortarActionPerformed(evt);
            }
        });
        jMenu2.add(jmItemCortar);

        jmItemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCopiar.setMnemonic('C');
        jmItemCopiar.setText("Copiar");
        jmItemCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCopiarActionPerformed(evt);
            }
        });
        jMenu2.add(jmItemCopiar);

        jmItemPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemPegar.setMnemonic('P');
        jmItemPegar.setText("Pegar");
        jMenu2.add(jmItemPegar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opciones ");

        jmnuFuente.setMnemonic('F');
        jmnuFuente.setText("Fuente");

        jmItemCourierNew.setText("CourierNew");
        jmnuFuente.add(jmItemCourierNew);

        jmItemnArial.setText("Arial");
        jmnuFuente.add(jmItemnArial);

        jmItemFPredeterminada.setText("FPredeterminada");
        jmnuFuente.add(jmItemFPredeterminada);

        jMenu3.add(jmnuFuente);

        jmnuTamaño.setMnemonic('T');
        jmnuTamaño.setText("Tamaño");

        jmItem16.setText("16");
        jmItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItem16ActionPerformed(evt);
            }
        });
        jmnuTamaño.add(jmItem16);

        jmItem24.setText("24");
        jmnuTamaño.add(jmItem24);

        jmItemPredeterminado.setText("Predeterminado");
        jmItemPredeterminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemPredeterminadoActionPerformed(evt);
            }
        });
        jmnuTamaño.add(jmItemPredeterminado);

        jMenu3.add(jmnuTamaño);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCortarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.cut();
    }//GEN-LAST:event_jmItemCortarActionPerformed

    private void jmItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItem16ActionPerformed

    private void jmItemPredeterminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemPredeterminadoActionPerformed
        // TODO add your handling code here:
        java.awt.Font f=jtxtaEditor.getFont();
        f=new java.awt.Font(f.getFamily()), f.getStyle(), fuentePr.getSize()
    }//GEN-LAST:event_jmItemPredeterminadoActionPerformed

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmItemSalirActionPerformed

    private void jmItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCopiarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.copy();
    }//GEN-LAST:event_jmItemCopiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmItem16;
    private javax.swing.JMenuItem jmItem24;
    private javax.swing.JMenuItem jmItemCopiar;
    private javax.swing.JMenuItem jmItemCortar;
    private javax.swing.JMenuItem jmItemCourierNew;
    private javax.swing.JMenuItem jmItemFPredeterminada;
    private javax.swing.JMenuItem jmItemPegar;
    private javax.swing.JMenuItem jmItemPredeterminado;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmItemnArial;
    private javax.swing.JMenu jmnuArchivo;
    private javax.swing.JMenu jmnuFuente;
    private javax.swing.JMenu jmnuTamaño;
    private javax.swing.JTextArea jtxtaEditor;
    // End of variables declaration//GEN-END:variables
}
